name: Update roadmap readme
on:
  issues:
    types: [labeled, unlabeled]
jobs:
  buildRoadmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Create chart post
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_CHANGE: TRUE
        run: npm run build-roadmap
